package HelloApp;


/**
* HelloApp/IHelloWorld.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* lunes 28 de febrero de 2022 12H35' CET
*/

public interface IHelloWorld extends IHelloWorldOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IHelloWorld
