package HelloApp;


/**
* HelloApp/IHelloWorldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* lunes 28 de febrero de 2022 12H35' CET
*/

public interface IHelloWorldOperations 
{
  String HelloWorld ();
  void shutdown ();
} // interface IHelloWorldOperations
